program: quantization.py
method: grid
parameters:

  hidden_layer_width:
    # values: [16, 32, 64, 128, 256, 512, 1024]
    values: [128]
  num_hidden_layers:
    # values: [1, 2, 3, 4]
    values: [2]
  optimizer_name:
    values: ['adam']
  batch_size:
    values: [128]
  lr:
    values: [0.001]
  dropout_prob:
    values: [0]
  weight_decay:
    values: [0]