program: distillation_comb.py
method: grid
parameters:

  hidden_layer_width:
    values: [1024, 2048]
  num_hidden_layers:
    values: [3, 4]
  optimizer_name:
    values: ['adam']
  batch_size:
    values: [64, 128]
  lr:
    values: [0.003]
  dropout_prob:
    values: [0]
  weight_decay:
    values: [0]