program: distillation_dist.py
method: grid
parameters:

  input_dim:
    values: [40]
  output_dim:
    values: [10]

  hidden_layer_width:
    values: [256, 512, 1024]
  num_hidden_layers:
    values: [1, 2, 3]
  optimizer_name:
    values: ['adam', 'sgd', 'rmsprop']
  batch_size:
    values: [64, 128, 256]
  lr:
    values: [0.01, 0.0032, 0.001]
  dropout_prob:
    values: [0.0, 0.2, 0.5]
  weight_decay:
    values: [0, 0.00001, 0.0001]