program: quantization.py
method: grid
parameters:

  hidden_layer_width:
    values: [512]
  num_hidden_layers:
    values: [2]
  optimizer_name:
    values: ['adam']
  batch_size:
    values: [32]
  lr:
    values: [0.003]
  dropout_prob:
    values: [0]
  weight_decay:
    values: [0]