program: distillation_dist.py
method: grid
parameters:

  input_dim:
    values: [40]
  output_dim:
    values: [10]
  hidden_layer_width:
    values: [300]
  num_hidden_layers:
    values: [1]

  optimizer_name:
    values: ['adam', 'sgd', 'rmsprop']
  batch_size:
    values: [32]
  lr:
    values: [0.0032]
  dropout_prob:
    values: [0.0]
  weight_decay:
    # values: [0, 1e-4, 1e-3]
    values: [0]