program: distillation_base.py
method: grid
parameters:
  dims:
    values: [[40, 500, 10]]
  batch_size:
    values: [32]
  lr:
    values: [0.0032]
  dropout_prob:
    values: [0.0]
  weight_decay:
    values: [0, 1e-4, 1e-3]