program: quantization.py
method: grid
parameters:

  hidden_layer_width:
    values: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
  num_hidden_layers:
    values: [1]
  optimizer_name:
    values: ['adam']
  batch_size:
    values: [128]
  lr:
    values: [0.001]
  dropout_prob:
    values: [0]
  weight_decay:
    values: [0]