program: distillation_comb.py
method: grid
parameters:

  hidden_layer_width:
    values: [1024]
  num_hidden_layers:
    values: [2]
  optimizer_name:
    values: ['adam']
  batch_size:
    values: [32]
  lr:
    values: [0.001]
  dropout_prob:
    values: [0]
  weight_decay:
    values: [0]